# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '8.DesignerQLineEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_Form(object):
    def __init__(self):
        self.widget = QtWidgets.QWidget(Form)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.label = QtWidgets.QLabel(self.widget)
        self.widget1 = QtWidgets.QWidget(Form)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget1)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(399, 130)

        self.widget.setGeometry(QtCore.QRect(10, 20, 381, 41))
        self.widget.setObjectName("widget")

        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit.setMaxLength(5)  # Public Functions
        self.lineEdit.textChanged[str].connect(self.event_line_edit_on_changed)  # Events

        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.widget1.setGeometry(QtCore.QRect(10, 70, 240, 25))
        self.widget1.setObjectName("widget1")

        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton.clicked.connect(self.event_change_label)

        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)

        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_3.clicked.connect(self.event_line_edit_clear)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Main Window - QLineEdit & QLabel"))
        self.label.setText(_translate("Form", "---"))
        self.pushButton.setText(_translate("Form", "Align Label"))
        self.pushButton_2.setText(_translate("Form", "Read Label"))
        self.pushButton_3.setText(_translate("Form", "Clear Line Edit"))

    def event_change_label(self):
        self.label.setText(self.lineEdit.text())
        self.lineEdit.setAlignment(Qt.AlignCenter)

    def event_line_edit_on_changed(self):
        self.label.setText(self.lineEdit.text())

    def event_line_edit_clear(self):
        self.lineEdit.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
