# Form implementation generated from reading ui file 'DesignerQListWidget.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget


class window(QWidget):
    def __init__(self):
        super().__init__()
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(windowQWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.listWidget1 = QtWidgets.QListWidget(windowQWidget)
        self.label1 = QtWidgets.QLabel(windowQWidget)
        self.label2 = QtWidgets.QLabel(windowQWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.pushButton1 = QtWidgets.QPushButton(windowQWidget)
        self.lineEdit1 = QtWidgets.QLineEdit(windowQWidget)
        self.pushButton2 = QtWidgets.QPushButton(windowQWidget)
        self.lineEdit2 = QtWidgets.QLineEdit(windowQWidget)
        self.pushButton3 = QtWidgets.QPushButton(windowQWidget)
        self.pushButton4 = QtWidgets.QPushButton(windowQWidget)
        self.pushButton6 = QtWidgets.QPushButton(windowQWidget)
        self.pushButton7 = QtWidgets.QPushButton(windowQWidget)
        self.lineEdit3 = QtWidgets.QLineEdit(windowQWidget)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(466, 488)

        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget1.setObjectName("listWidget1")
        self.label1.setObjectName("label1")
        self.label2.setObjectName("label2")
        self.pushButton1.setObjectName("pushButton1")
        self.lineEdit1.setObjectName("lineEdit1")
        self.pushButton2.setObjectName("pushButton2")
        self.lineEdit2.setObjectName("lineEdit2")
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton6.setObjectName("pushButton6")
        self.pushButton7.setObjectName("pushButton7")
        self.lineEdit3.setObjectName("lineEdit3")

        self.verticalLayout_2.addWidget(self.listWidget1)
        self.verticalLayout_2.addWidget(self.label1)
        self.verticalLayout_2.addWidget(self.label2)
        self.verticalLayout.addWidget(self.pushButton1)
        self.verticalLayout.addWidget(self.lineEdit1)
        self.verticalLayout.addWidget(self.pushButton2)
        self.verticalLayout.addWidget(self.lineEdit2)
        self.verticalLayout.addWidget(self.pushButton3)
        self.verticalLayout.addWidget(self.pushButton4)
        self.verticalLayout.addWidget(self.pushButton6)
        self.verticalLayout.addWidget(self.pushButton7)
        self.verticalLayout.addWidget(self.lineEdit3)

        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton1.clicked.connect(self.add_item)
        self.pushButton2.clicked.connect(self.insert_item)
        self.listWidget1.itemClicked.connect(self.info_current_item)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QWidget - QListBox"))
        self.label1.setText(_translate("Form", "Label Count Items"))
        self.label2.setText(_translate("Form", "Label Current Row"))
        self.pushButton1.setText(_translate("Form", "Insert Items"))
        self.pushButton2.setText(_translate("Form", "Edit Items"))
        self.pushButton3.setText(_translate("Form", "Remove Items"))
        self.pushButton4.setText(_translate("Form", "Clear List"))
        self.pushButton6.setText(_translate("Form", "Sort Items"))
        self.pushButton7.setText(_translate("Form", "Find Items"))

    def add_item(self):
        self.listWidget1.addItem(self.lineEdit1.text())
        self.lineEdit1.clear()
        self.lineEdit1.setFocus()
        self.label1.setText("Total Items : " + str(self.listWidget1.count()))

    def insert_item(self):
        self.listWidget1.insertItem(3, "Data in row three")

    def info_current_item(self):
        item = self.listWidget1.currentItem()
        self.label2.setText(item.text())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication([])
    windowQWidget = QWidget()
    gui = window()
    gui.setupUi(windowQWidget)
    windowQWidget.show()
    sys.exit(app.exec())

